# TREATMENTS = [
#   'Ablation',
#   'Electric Countershock',
#   'anticoagulation',
#   'Stroke prevention',
#   'Cardiac ablation',
#   'Warfarin',
#   'Amiodarone',
#   'Anti-Arrhythmia Agents',
#   'Operative Surgical Procedures',
#   'Maze operation',
#   'Radiofrequency ablation',
#   'Digoxin',
#   'Procedures',
#   'Anticoagulant therapy',
#   'Anticoagulants',
#   'Propafenone',
#   'Catheter Ablation, Radiofrequency',
#   'Verapamil',
#   'Aspirin',
#   'Oral anticoagulants',
#   'Flecainide',
#   'Prophylactic treatment',
#   'Diltiazem',
#   'Isolation procedure',
#   'Management procedure',
#   'Sotalol',
#   'Direct current cardioversion',
#   'Intervention regimes',
#   'Hospitalization',
#   'Internal cardioversion',
#   'Cox-maze procedure',
#   'Quinidine',
#   'Exercise',
#   'Implantation procedure',
#   'Cardiac resynchronisation therapy',
#   'Adrenergic beta-Antagonists',
#   'follow-up',
#   'Placebos',
#   'Pharmacotherapy',
#   'Assessment procedure',
#   'ibutilide',
#   'Vitamin K antagonist',
#   'dofetilide',
#   'Procainamide',
#   'Cryosurgery',
#   'Application procedure',
#   'Stimulation procedure',
#   'Defibrillators, Implantable',
#   'Elective electrical cardioversion of arrhythmia, external',
#   'Bepridil',
# ]

# ONE = 'http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22Procedures%22'
# TWO = 'http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22atrial+fibrillation%22+%22Procedures%22'

TREATMENTS = [
  '-plasty',
  '2-aminofluorene',
  '3-Iodobenzylguanidine',
  'Ablation',
  'Ablation Catheters',
  'Acenocoumarol',
  'acetovanillone',
  'Acupuncture procedure',
  'Adenosine',
  'Adenosine Diphosphate Receptor Inhibitors',
  'Adjustment Action',
  'adjuvant therapy',
  'Administration, Oral',
  'Adrenal Cortex Hormones',
  'Adrenergic beta-Antagonists',
  'Advice',
  'Ajmaline',
  'Albuterol',
  'Aldosterone',
  'Aldosterone Antagonists',
  'Aldosterone Receptor Antagonists',
  'Alteplase',
  'Alternative Therapies',
  'amidronate',
  'Aminophylline',
  'Amiodarone',
  'Amiodarone hydrochloride',
  'Amlodipine',
  'Amputation',
  'Anesthesia procedures',
  'Anesthesia, Epidural',
  'Angiopoietin-2',
  'Angiotensin II',
  'Angiotensin II receptor antagonist',
  'Angiotensin II Type 1 Receptor Blockers',
  'Angiotensin-Converting Enzyme Inhibitors',
  'Angiotensins',
  'Annuloplasty',
  'Anti-Anxiety Agents',
  'Anti-Arrhythmia Agents',
  'Anti-Bacterial Agents',
  'Anti-Inflammatory Agents',
  'Anti-Inflammatory Agents, Non-Steroidal',
  'Antibiotics',
  'Anticoagulant drug monitoring',
  'Anticoagulant therapy',
  'Anticoagulants',
  'anticoagulation',
  'ANTICOAGULATION TREATMENT',
  'Antidepressive Agents',
  'Antifibrinolytic Agents',
  'Antihypertensive Agents',
  'Antihypertensive therapy',
  'Antiinflammatory therapy',
  'Antioxidants',
  'Antiplatelet Agents',
  'Antiplatelet therapy',
  'Antithrombin III',
  'aortic balloon pump',
  'Aortic valve replacement NOS',
  'Application procedure',
  'Aprindine',
  'Arsenal',
  'Arteriovenous graft',
  'Arthroplasty',
  'Arthroplasty, Replacement, Hip',
  'Arthroplasty, Replacement, Knee',
  'Ascorbic Acid',
  'asparaginase/prednisone/vincristine protocol',
  'Aspirin',
  'Assessment procedure',
  'Atenolol',
  'atorvastatin',
  'Atrial cardioversion',
  'Atrial operation',
  'Atrial overdrive pacing',
  'Atropine',
  'Autologous Stem Cell Transplantation',
  'Autonomic Denervation',
  'azimilide',
  'azimilide dihydrochloride',
  'Balloon Dilatation',
  'Balloon dilatation catheter',
  'Balloon mitral valvotomy',
  'Balloon Occlusion',
  'Balloon Valvuloplasty',
  'Bands',
  'benazepril',
  'Bepridil',
  'Bepridil hydrochloride',
  'Beta blocker prophylaxis',
  'BETA BLOCKER TREATMENT',
  'Betapace AF',
  'Betaxolol',
  'bidisomide',
  'Biological Response Modifier Therapy',
  'Biomedical Monitors',
  'Bisoprolol',
  'Blood Pressure Monitors',
  'Boards',
  'Bone plates',
  'Bone Wires',
  'Booster',
  'Brain natriuretic peptide',
  'Bretylium Tosylate',
  'bucindolol',
  'Butorphanol Tartrate',
  'Bypass',
  'Bypass graft',
  'Bypass surgery',
  'Caffeine',
  'Calcium Channel Blockers',
  'candesartan',
  'candesartan cilexetil',
  'Cannulation',
  'capecitabine',
  'Cardiac ablation',
  'Cardiac Glycosides',
  'Cardiac Monitors',
  'Cardiac pacing NOS',
  'Cardiac rehabilitation',
  'Cardiac resynchronisation therapy',
  'Cardiac Stimulators',
  'Cardiac Surgery procedures',
  'Cardiopulmonary Bypass',
  'Cardiovascular Agents',
  'Cardiovascular Surgical Procedures',
  'Carotid sinus massage',
  'carvedilol',
  'Catheter Ablation, Percutaneous',
  'Catheter Ablation, Radiofrequency',
  'Catheter Ablation, Transvenous',
  'catheter device',
  'catheter management',
  'Catheter procedure',
  'Catheterization',
  'Catheters, Cardiac, Ablation',
  'Catheters, Electrode',
  'Catheters, Vascular, Retrieval, Basket',
  'Cell hybridization',
  'Cell Therapy',
  'Central venous catheter',
  'certoparin',
  'Channel Blockers',
  'Charts',
  'chemosensitization/potentiation',
  'chronic anticoagulation',
  'cifenline',
  'Cigarette Smoking',
  'Cilazapril',
  'cilostazol',
  'cisplatin/cyclophosphamide/doxorubicin/etoposide chemotherapy protocol',
  'Clamp',
  'Class Ia antiarrhythmic drug',
  'Class Ic antiarrhythmic drug',
  'Class III antiarrhythmic drug',
  'Clinical Management',
  'Clinical Treatment',
  'Clipping',
  'Clonidine',
  'clopidogrel',
  'Closure of defect of interatrial septum NOS',
  'Coagulants',
  'Coagulation procedure',
  'Cold Therapy',
  'Combined Modality Therapy',
  'Complete excision',
  'Complex procedure',
  'Conscious Sedation',
  'Conservative therapy',
  'Continuous ECG monitoring',
  'Continuous Intravenous Infusion',
  'Continuous Positive Airway Pressure',
  'Conventional Surgery',
  'Convulsive therapy',
  'Cordarone',
  'Coronary Artery Bypass Surgery',
  'Coronary revascularisation',
  'Corridor operation',
  'Coumadin',
  'coumarin',
  'Coumarins',
  'Counseling',
  'Covers',
  'Cox-maze procedure',
  'CRT-D',
  'Cryosurgery',
  'Curative Surgery',
  'cytarabine/daunorubicin protocol',
  'Cytokine therapy',
  'Dalteparin',
  'DC shock',
  'DEFIBRILLATOR, IMPLANTABLE, DUAL-CHAMBER',
  'Defibrillators',
  'Defibrillators, Implantable',
  'DELIVER',
  'Denervation',
  'Detection',
  'Device therapy',
  'Dexverapamil',
  'Diagnosis',
  'Diagnostic device',
  'Dialysis procedure',
  'Diethylstilbestrol',
  'digitalin',
  'Digitalis Glycosides',
  'Digitalis preparation',
  'DIGITALIS THERAPY',
  'Digoxin',
  'DIGOXIN TREATMENT',
  'dihydropyridine',
  'Diltiazem',
  'Dimethoxyamphetamine',
  'Diphosphonates',
  'Direct current cardioversion',
  'Direct current therapy',
  'Direct thrombin inhibitor',
  'DISCHARGE PROGRAM',
  'Discontinuation',
  'Disease Management',
  'Disopyramide',
  'Dissection',
  'Diuretics',
  'Diversion procedure',
  'Division',
  'Dobutamine',
  'docetaxel',
  'Docosahexaenoic Acids',
  'Documented',
  'dofetilide',
  'Double valve replacement',
  'Drainage procedure',
  'dronedarone',
  'Drug eluting stent',
  'Drug Infusion Systems',
  'Drug Monitoring',
  'Drugs, Investigational',
  'Dual Chamber',
  'E-Therapy',
  'early identification',
  'Early Mobilization',
  'Echocardiographs',
  'Echocardiography',
  'educational intervention',
  'Eicosapentaenoic Acid',
  'Elective electrical cardioversion of arrhythmia, external',
  'Elective procedure',
  'Electric Countershock',
  'Electric Stimulation Therapy',
  'Electroanatomical Mapping Systems',
  'Electrocardiographic monitoring',
  'Electrocardiographic recorders',
  'Electrolyte replacement',
  'Embolectomy',
  'Embolization, Therapeutic',
  'Emergency CABG',
  'Emergency Care',
  'Emergency medical service',
  'Emergency visit',
  'Empirical therapy',
  'Enalapril',
  'Encainide',
  'Endarterectomy, Carotid',
  'Endocrine therapy',
  'Enoxaparin',
  'eplerenone',
  'Epoprostenol',
  'Erythrocyte Transfusion',
  'Erythromycin',
  'esmolol',
  'Esophagectomy',
  'Ethanol',
  'Excision',
  'Excision of muscle NOS',
  'Exercise',
  'Exercise, Isometric',
  'Exploration procedure',
  'Expression procedure',
  'Extraction',
  'Extrapleural pneumonectomy',
  'ezetimibe',
  'Factor VIII',
  'Falepsin',
  'Fatty Acids, Omega-3',
  'FAVOR',
  'Fibrinolytic Agents',
  'Fish Oils',
  'Flecainide',
  'Flecainide Acetate',
  'flestolol',
  'flosequinan',
  'fluorophore',
  'follow-up',
  'fondaparinux',
  'Forecast of outcome',
  'Formation of pericardial baffle, interatrial',
  'fragmentation procedure',
  'Frame',
  'Gallopamil',
  'General Anesthesia',
  'geranylgeranylacetone',
  'Glucose',
  'Glycerol',
  'Group Psychotherapy',
  'Guideline Adherence',
  'HA 7',
  'Handball',
  'Health Care',
  'Heart Arrest, Induced',
  'HEART RATE TARGET',
  'Heart Transplantation',
  'Heart Valve Prosthesis',
  'Heart valve replacement',
  'HEART-VALVE, MECHANICAL',
  'Heparin',
  'Heparin, Low-Molecular-Weight',
  'High frequency ablation',
  'Hospital Administration',
  'Hospital admission',
  'Hospital Readmissions',
  'Hospitalization',
  'Hydralazine',
  'hydrochloride',
  'hydroquinidine',
  'Hydroxymethylglutaryl-CoA Reductase Inhibitors',
  'ibutilide',
  'Illicit Drugs',
  'Imaging Techniques',
  'Immobilization',
  'Implant, pacemaker',
  'Implantation procedure',
  'Implants',
  'Incision and drainage',
  'Incision of sternum',
  'Individual psychotherapy',
  'indobufen',
  'Induction',
  'Indwelling Catheter',
  'Inferential Current Treatment',
  'Inflation procedure',
  'Infusion procedures',
  'Injection procedure',
  'Inotropic agent',
  'Insulin',
  'Insurance, Long-Term Care',
  'Internal cardioversion',
  'Intervention regimes',
  'Intra-aortic balloon pump device',
  'Intra-Aortic Balloon Pumping',
  'Intravenous sedation',
  'Intravenous therapy',
  'Introduction procedure',
  'invasive treatment',
  'investigation',
  'Iodine',
  'Ion Channel',
  'Iontophoresis',
  'irbesartan',
  'Ischemic Preconditioning',
  'Isolation procedure',
  'Isoproterenol',
  'Isotonic exercise',
  'Kinilentin',
  'Kordaron',
  'landiolol',
  'Leads',
  'Lidocaine',
  'Lidoflazine',
  'Lifestyle counseling',
  'Ligation',
  'Lipid-lowering therapy',
  'Lobectomy',
  'long-term care',
  'Long-term drug therapy',
  'Longterm Follow-up',
  'Losartan',
  'Magnesium',
  'Magnesium Sulfate',
  'Magnetocardiographs',
  'Maintenance therapy',
  'Managed Care',
  'Management procedure',
  'Maze operation',
  'Mechanical ventilation',
  'Medical therapy',
  'Medication Management',
  'Medications, blood',
  'Medications, cardiovascular',
  'melagatran',
  'Mercury sphygmomanometer',
  'Metoprolol',
  'metoprolol succinate',
  'Metric',
  'Metyrapone',
  'Mexiletine',
  'Mibefradil',
  'Microelectrodes',
  'Mitral valve operation',
  'Mitral valve prosthesis',
  'Mitral valve replacement NOS',
  'Mitral valvotomy',
  'Monitoring Device',
  'Monitoring Systems',
  'Moricizine',
  'N,N-dimethylarginine',
  'Nafarelin',
  'National Hospital Discharge Survey',
  'nebivolol',
  'Nebulizers',
  'Neuromuscular Blocking Agents',
  'Neurostimulation procedures of spinal cord tissue',
  'nibentan',
  'Nifedipine',
  'NIP142',
  'Non-cardioselective beta-blocker',
  'Norepinephrine',
  'Notifications NOS',
  'Novocainamide',
  'Occluders',
  'Open approach',
  'Open heart surgery',
  'Operative procedure on coronary arteries',
  'Operative Surgical Procedures',
  'Opium',
  'Opportunistic screening',
  'Oral anticoagulants',
  'Oral form verapamil',
  'Oral medication',
  'ORALIT',
  'Ouabain',
  'Outpatient procedure',
  'p-Aminosalicylic Acid',
  'PACEMAKER PERMANENT',
  'Pacemakers',
  'Pacerone',
  'Pads',
  'Pain management',
  'Palliative Care',
  'Palliative procedure',
  'patient care',
  'Patient Care Management',
  'Patient Discharge',
  'Patient History',
  'Patient identification',
  'Patient Isolation',
  'Patient Selection',
  'Percutaneous balloon mitral valvuloplasty',
  'Percutaneous coronary intervention',
  'Percutaneous valvuloplasty',
  'Pericardiotomy',
  'Pharmacological Treatment',
  'Pharmacotherapy',
  'Phenprocoumon',
  'Photochemotherapy',
  'Phototherapy',
  'Physical Examination',
  'PHYSICAL PERFORMANCE',
  'pilsicainide',
  'Pindolol',
  'pioglitazone',
  'Pirenzepine',
  'pirfenidone',
  'Placebos',
  'Plastic operation on muscle',
  'Play',
  'Pleurectomy',
  'Plug',
  'Position change',
  'Positive pressure therapy',
  'Potassium Channel Blockers',
  'Pravastatin',
  'Prenatal Testing',
  'Prescription of prophylactic anticoagulant',
  'prescription procedure',
  'Prescriptions, Drug',
  'prevention evaluation',
  'prevention of disorder',
  'Primary Health Care',
  'Primary Prevention',
  'proadrenomedullin',
  'Probes',
  'Probucol',
  'Procainamide',
  'Procedure on heart',
  'Procedures',
  'Procedures on veins',
  'Propafenone',
  'Propafenone Hydrochloride',
  'Prophylactic treatment',
  'Propofol',
  'Propranolol',
  'Prostaglandins',
  'Prosthesis',
  'Prosthetic replacement',
  'Prosthetic valve',
  'Protamines',
  'Psychotherapy, Multiple',
  'Puncture procedure',
  'Quinidine',
  'Quinidine Sulfate',
  'Radiofrequency ablation',
  'Radiofrequency Ablation Systems',
  'Ramipril',
  'ranolazine',
  'ranpirnase',
  'Reading',
  'REBREATHING',
  'Recombinant Monocyte Chemoattractant Protein-1',
  'Reconstructive Surgical Procedures',
  'Recorder',
  'Rehabilitation therapy',
  'Relaxation',
  'remifentanil',
  'Removal of endotracheal tube',
  'Removes',
  'Renin-angiotensin-aldosterone System Inhibitors',
  'Repair of mitral valve',
  'Repair of tricuspid valve',
  'Reparative closure',
  'Repeat Surgery',
  'Reperfusion Therapy',
  'Replacement of mitral valve with tissue graft',
  'Reporting',
  'Rest',
  'resveratrol',
  'Revascularization - action',
  'rilmakalim',
  'Risk Assessment',
  'Risk Management',
  'Risk Reduction',
  'RMS',
  'Robotic Systems',
  'rosuvastatin',
  'Rotundium',
  'Routine procedure',
  'Scanning Systems',
  'Screening procedure',
  'Screening Tests',
  'Secondary prevention',
  'Secondary procedure',
  'Self-Management',
  'Semiconductor laser device',
  'Sensors',
  'Sleeves',
  'Sodium Channel Blockers',
  'Sodium Chloride',
  'Sotalol',
  'Sphygmomanometers',
  'Spironolactone',
  'split brain',
  'Sports',
  'Stabilization',
  'Stents, Vascular, Coronary',
  'Steroid therapy',
  'Stimulation procedure',
  'Streptokinase',
  'Stroke prevention',
  'stroke therapy',
  'Superoxide Dismutase',
  'Support, device',
  'Surgical incisions',
  'Surgical Management',
  'Surgical Procedures, Elective',
  'Surgical Procedures, Endoscopic',
  'Surgical Procedures, Minimally Invasive',
  'Surgical Procedures, Thoracoscopic',
  'Surgical repair',
  'Surgical Replantation',
  'Suture ligation',
  'Sympathectomy',
  'Symptom control',
  'Taking medication',
  'tedisamil',
  'Telemedicine',
  'telmisartan',
  'Termination of pregnancy',
  'Testosterone',
  'Theophylline',
  'Therapeutic agent',
  'Therapeutic device, NOS',
  'Therapeutic Effect',
  'Therapeutic Intervention',
  'Therapy, Computer-Assisted',
  'Thiazolidinediones',
  'Thoracic Surgical Procedures',
  'Thrombin',
  'Thrombin Inhibitors',
  'Thromboembolectomy',
  'Thrombolytic Therapy',
  'Ticlopidine',
  'Total pharyngolaryngectomy',
  'Transcutaneous Electric Nerve Stimulation',
  'Transducers',
  'Transjugular intrahepatic portosystemic shunt procedure',
  'Transplantation',
  'Transplantation, Autologous',
  'Treatment Guidelines',
  'treatment method',
  'Treatment Protocols',
  'triflusal',
  'Ultrasonic Therapy',
  'Ultrasound Ablation Catheters',
  'Univer',
  'valsartan',
  'Verapamil',
  'VERAPAMIL TREATMENT',
  'Video-Assisted Surgery',
  'Visit, outpatient',
  'Vitamin E',
  'Vitamin K',
  'Vitamin K antagonist',
  'Vitamin prophylaxis',
  'Vitamin supplementation',
  'von Willebrand Factor',
  'Warfarin',
  'Warfarin Sodium',
  'WARFARIN TREATMENT',
  'Wavefront analysis',
  'Xamoterol',
  'ximelagatran',
  'zoledronic acid',
  'Zonal',
  '{PROVIDER}'
]

require 'net/http'
require 'rexml/rexml'
require 'rexml/document'

def get_count(url)
  uri = URI(url)
  s = Net::HTTP.get(uri)


  doc = REXML::Document.new(s)
  count = doc.elements['eSearchResult\Count'].first.text
end



TREATMENTS.each do |t|
  t = t.gsub(' ', '+')
  first = get_count("http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22#{t}%22")
  second = get_count("http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22atrial+fibrillation%22+%22#{t}%22")

  puts "#{t},#{second.to_f / first.to_f}"
end