# ONE = 'http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22Procedures%22'
# TWO = 'http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22atrial+fibrillation%22+%22Procedures%22'

CONGEST_HEART_FAILURE_TREATMENTS = [
  "-plasty",
  "1,4-dihydro-2,6-dimethyl-4-(3-nitrophenyl)-3,5-pyridinedicarboxylic acid dimethyl ester",
  "1-(N-(2-hydroxy-5-azidobenzoyl)-2-aminoethyl)-4-(N-hydroxysuccinimidyl)succinate",
  "15 AU81",
  "2,4-thiazolidinedione",
  "2-methyl-5,6,7,8-tetrahydro-6-(methylamino)-1,2-naphthalenediyl ester hydrochloride",
  "25-hydroxyvitamin D",
  "3-(2,2,2-trimethylhydrazine)propionate",
  "3-Iodobenzylguanidine",
  "4-Aminobenzoic Acid",
  "4-Aminopyridine",
  "5,6,7,8-tetrahydrobiopterin",
  "A 81988",
  "abacavir",
  "Ablation",
  "acadesine",
  "Accelerometers",
  "Accupro",
  "Acetaminophen",
  "Acetazolamide",
  "acetohydroxamic acid",
  "Acetone",
  "acetorphan,",
  "Acetyl-L-Carnitine",
  "Acetylcholine",
  "Acetylcysteine",
  "Aconite",
  "Active monitoring",
  "Activins",
  "Activities of Daily Living",
  "Acupuncture procedure",
  "acute care",
  "Adenine Nucleotides",
  "Adenosine",
  "adenosine receptor antagonist",
  "Adenosine Triphosphate",
  "Adjunctive care",
  "Adjustment Action",
  "adjuvant therapy",
  "Administration, Oral",
  "Admit hospital emergency NOS",
  "Adrenal Cortex Hormones",
  "Adrenergic Agents",
  "Adrenergic Agonists",
  "Adrenergic alpha-Antagonists",
  "Adrenergic Antagonists",
  "Adrenergic beta-Agonists",
  "Adrenergic beta-Antagonists",
  "adrenomedullin",
  "Advance",
  "Advance Care Planning",
  "Advice",
  "Advice on smoking",
  "Aftercare",
  "Agonist drug",
  "agonists",
  "Airway management",
  "alacepril",
  "Albunex",
  "Albuterol",
  "Aldactacine",
  "Aldactone",
  "Aldosterone",
  "Aldosterone Antagonists",
  "Aldosterone Receptor Antagonists",
  "aliskiren",
  "allapinin",
  "Alleviating anxiety",
  "Allogeneic bone marrow transplantation",
  "Allografting",
  "Allopurinol",
  "alpha Tocopherol",
  "alpha-atrial natriuretic peptide, human",
  "alpha-Melanocyte stimulating hormone",
  "alpha-Methyltyrosine",
  "alpha-trinositol",
  "Alprostadil",
  "Alteplase",
  "Alternative Therapies",
  "ambulatory care services",
  "Amiloride",
  "Amines, Sympathomimetic",
  "Amino acid supplement",
  "Amino Acids",
  "Amino-terminal pro-brain natriuretic peptide",
  "Aminophylline",
  "Amiodarone",
  "Amlodipine",
  "Amlodipine Besylate",
  "Amphetamine",
  "Amputation",
  "anakinra",
  "Analgesia, Epidural",
  "Analgesics",
  "Analog",
  "Analyzer",
  "Anaprilin",
  "Anastomosis of vena cava to pulmonary artery",
  "Androgen therapy",
  "Androgens",
  "Anesthesia procedures",
  "Anesthesia, Epidural",
  "Anesthetics",
  "Aneurysmectomy",
  "Angioplasty",
  "Angioplasty, Balloon",
  "Angioplasty, Transluminal, Percutaneous Coronary",
  "Angiopoietin-2",
  "Angiotensin converting enzyme inhibitor therapy",
  "Angiotensin II",
  "Angiotensin II receptor antagonist",
  "Angiotensin II Type 1 Receptor Blockers",
  "Angiotensin Receptor Antagonists",
  "Angiotensin-Converting Enzyme Inhibitors",
  "Angiotensins",
  "Annuloplasty",
  "antagonists",
  "Anti-Anxiety Agents",
  "Anti-Arrhythmia Agents",
  "anti-cytokine therapy",
  "Anti-Inflammatory Agents",
  "Anti-Inflammatory Agents, Non-Steroidal",
  "Anti-Obesity Agents",
  "anti-tumor necrosis factor therapy",
  "antiarrhythmic peptide",
  "Antibiotic Prophylaxis",
  "Antibiotic therapy",
  "Antibiotics",
  "antibody therapy",
  "Anticholinergic bronchodilators",
  "Anticoagulant therapy",
  "Anticoagulants",
  "anticoagulation",
  "Antidepressant therapy",
  "Antidepressive Agents",
  "Antidiabetics",
  "ANTIDIURETICS",
  "Antihypertensive Agents",
  "Antihypertensive therapy",
  "Antiinflammatory therapy",
  "Antilipemic Agents",
  "Antineoplastic Agents",
  "Antioxidants",
  "Antiplatelet Agents",
  "Antiplatelet therapy",
  "Antipsychotic Agents",
  "Antipyrine",
  "Antiretroviral Therapy, Highly Active",
  "Antithrombin III",
  "aortic balloon pump",
  "Aortic valve replacement NOS",
  "Aortopexy",
  "Aortoplasty",
  "Application procedure",
  "AR L100",
  "AR-C239",
  "AR-L 115 BS",
  "AR-L115",
  "Arginine",
  "Argipressin",
  "Arsenal",
  "Art Therapy",
  "Arterial catheterization",
  "Arterial perfusion",
  "Arteriovenous anastomosis procedure",
  "artesunate",
  "Artificial cardiac pacemaker",
  "Artificial Ventricle",
  "ascorbate",
  "Ascorbic Acid",
  "Aspirin",
  "Assessment procedure",
  "Assisted breathing",
  "Assisted Circulation",
  "Atacand",
  "Atenolol",
  "atorvastatin",
  "Atrial appendage excision",
  "Atrial Natriuretic Factor",
  "atrial natriuretic factor prohormone",
  "Atrioventricular sequential pacing",
  "Atropine",
  "Augmentation procedure",
  "Autologous bone marrow transplant",
  "Autologous Stem Cell Transplantation",
  "Automatic cardiac defibrillator",
  "Automatic Implantable Cardioverter-Defibrillators",
  "Autonomic Denervation",
  "Avapro",
  "Axillary-femoral arterial bypass",
  "Azathioprine",
  "azimilide",
  "azosemid",
  "B HT920",
  "B-HT 933",
  "Balloon Dilatation",
  "Balloon Embolization",
  "Balloon mitral valvotomy",
  "Balloon Valvuloplasty",
  "Banding procedure",
  "Bands",
  "Bariatric Surgery",
  "Bathing",
  "Baths, Finnish",
  "Baths, Water",
  "BAY y 5959",
  "Bay-K-8644",
  "BDF 9148",
  "Bed rest",
  "Bedside Technology",
  "Behavior Control",
  "Behavior Therapy",
  "Bemecor",
  "benazepril",
  "Benazepril hydrochloride",
  "Bendroflumethiazide",
  "Benzbromarone",
  "Benzodiazepines",
  "Berberine",
  "Beta 1 blocking agent",
  "beta adrenergic agent",
  "BETA BLOCKER TREATMENT",
  "Beta-2",
  "beta-2 Adrenergic Receptors",
  "beta-adrenergic receptor kinase inhibitory peptide",
  "beta-Lipotropin",
  "bevacizumab",
  "BG 9719",
  "Bi-level airway pressure",
  "Bicycle ergometer",
  "Bidil",
  "Bilevel positive airway pressure",
  "Biliopancreatic Diversion",
  "Biofeedback",
  "Biogenic Amines",
  "Biological blood vessel prosthesis",
  "Biological Response Modifiers",
  "Biomedical Monitors",
  "Bisoprolol",
  "Bisoprolol Fumarate",
  "Biventricular assist device",
  "Blood Component Removal",
  "Blood Substitutes",
  "Blood Transfusion",
  "Bloodletting",
  "BMS 186716",
  "Boards",
  "Bone Marrow Cell Transplantation",
  "Bone Marrow Stem Cell Transplantation",
  "Bone Marrow Transplantation",
  "bosentan",
  "BPC 157",
  "BQ 123",
  "Bradykinin",
  "Brain natriuretic peptide",
  "Breathing Exercises",
  "brief intervention",
  "BRL 37344",
  "Bromocriptine",
  "Bronchodilator Agents",
  "BTS 49465",
  "bucindolol",
  "Bucladesine",
  "Bumetanide",
  "bunazosin",
  "bunitrolol",
  "Bupropion",
  "Burinex",
  "Burinex K",
  "butizide",
  "butopamine",
  "Bypass",
  "Bypass graft",
  "Bypass surgery",
  "Caffeine",
  "Calcitonin Gene-Related Peptide",
  "Calcitriol",
  "Calcium Channel Blockers",
  "Calcium Gluconate",
  "calcium lactate",
  "Calcium salt",
  "Cancer Treatment",
  "candesartan",
  "candesartan cilexetil",
  "candoxatril",
  "candoxatrilat",
  "Cannulae, Nasal",
  "Cannulation",
  "Canrenone",
  "Capoten",
  "Capsaicin",
  "Captopril",
  "carbazeran",
  "Carbonic Anhydrase Inhibitors",
  "Cardiac ablation",
  "Cardiac care",
  "Cardiac drug",
  "Cardiac Glycosides",
  "Cardiac implant device",
  "Cardiac pacing NOS",
  "Cardiac rehabilitation",
  "Cardiac rehabilitation therapy",
  "Cardiac resynchronisation therapy",
  "Cardiac Surgery procedures",
  "Cardiectomy",
  "cardiodilatin",
  "Cardiology service",
  "Cardiomyopexy",
  "Cardiomyoplasty",
  "Cardiopulmonary Bypass",
  "Cardiopulmonary bypass circuit",
  "Cardiotonic Agents",
  "Cardiovascular Agents",
  "Cardiovascular monitoring",
  "Cardiovascular rehabilitation",
  "Cardiovascular therapy",
  "Care given by nurses",
  "CARE MAINTENANCE",
  "Care of intensive care unit patient",
  "Care provision regimes",
  "cariporide",
  "Carnitine",
  "carvedilol",
  "CAS 936",
  "case control",
  "Castration",
  "Catheter Ablation, Radiofrequency",
  "catheter device",
  "Catheterization",
  "Catheterization of right heart",
  "Catheters, Esophageal",
  "Catheters, Tenckhoff",
  "celecoxib",
  "Celiprolol",
  "Cell Therapy",
  "Cell Transplantation",
  "Central Nervous System Stimulants",
  "Central venous catheter",
  "Cesarean section",
  "cesium chloride",
  "CGP 48506",
  "CGS 14831",
  "CGS 30440",
  "Chambers",
  "Channel Blockers",
  "ChanSu",
  "Chart evaluation by healthcare professional",
  "Charts",
  "Chemoembolisation",
  "chemosensitization/potentiation",
  "Chemotherapeutic agent",
  "CHEMOTHERAPY DOXORUBICIN",
  "Chemotherapy, Adjuvant",
  "Chemotherapy-Oncologic Procedure",
  "CHEST PAIN HOSPITALIZATION",
  "Chinese herbal medicine",
  "Chinese herbs",
  "chlorethylclonidine",
  "Chloroquine",
  "Chlorothiazide",
  "Chlorthalidone",
  "Cholecalciferol",
  "Cholecystectomy",
  "chromanol",
  "Chromogranin A",
  "chronic anticoagulation",
  "Chymosin",
  "CI 914",
  "CI 930",
  "CI 930 hydrochloride",
  "Cialis",
  "cicloprolol",
  "cifenline",
  "Cigarette Smoking",
  "Cilazapril",
  "cilostazol",
  "cinacalcet",
  "Circulation, Artificial",
  "Citrate",
  "Class III antiarrhythmic drug",
  "Clenbuterol",
  "Clinic Visits",
  "Clinical act of insertion",
  "Clinical Management",
  "Clinical Protocols",
  "Clinical Treatment",
  "clofilium",
  "Clonidine",
  "Clonidine Hydrochloride",
  "clopidogrel",
  "Close observation",
  "Clozapine",
  "Coagulants",
  "Cocaine",
  "coenzyme Q10",
  "COF protocol",
  "Cognitive Therapy",
  "Colchicine",
  "colforsin daropate",
  "Combination Drug Therapy",
  "Combined Modality Therapy",
  "Communication interventions",
  "Complementary therapies",
  "Comprehensive Health Care",
  "Compression procedure",
  "Concentrators",
  "congener",
  "conivaptan",
  "Conservative therapy",
  "Constriction procedure",
  "Consultation",
  "Consultation, specialist",
  "Consulting with",
  "Continuous hemodiafiltration",
  "Continuous hemofiltration",
  "Continuous infusion",
  "Continuous Intravenous Infusion",
  "Continuous Positive Airway Pressure",
  "Continuous venovenous hemodiafiltration",
  "Continuous venovenous hemofiltration",
  "Contraceptive methods",
  "Conventional Surgery",
  "Convulsive therapy",
  "copeptins",
  "Copper",
  "Corinfar",
  "Coronary angioplasty",
  "Coronary Artery Bypass Surgery",
  "Coronary revascularisation",
  "Coronary vasodilator",
  "Corotrope",
  "Corticotropin",
  "Corticotropin-Releasing Hormone",
  "Corvaton",
  "Corwin",
  "Coude Catheters",
  "Counseling",
  "Counterpulsation",
  "Counterpulsation, External",
  "Covered Stents",
  "CP 191166",
  "CPG-ODN",
  "crataegus extract",
  "Creation of peritoneovascular shunt",
  "Crisis Intervention",
  "CRT-D",
  "Cryosurgery",
  "CTN",
  "Curcumin",
  "CVT 124",
  "Cyclizine",
  "Cyclooxygenase 2 Inhibitors",
  "Cyclooxygenase Inhibitors",
  "Cyclopenthiazide",
  "Cyclophosphamide",
  "cyclophosphamide/doxorubicin protocol",
  "Cyclosporine",
  "cyclovirobuxine D",
  "cytarabine/daunorubicin protocol",
  "cytokine",
  "Cytokine therapy",
  "Cytoprotective agent",
  "Cytotoxic agent",
  "Dacarbazine",
  "Daily Activities",
  "Dantrolene",
  "darbepoetin alfa",
  "darusentan",
  "DC shock",
  "deferiprone",
  "Defibrillators",
  "Defibrillators, Implantable",
  "delapril",
  "Delayed-Action Preparations",
  "Demand pacing",
  "Demeclocycline",
  "Denervation",
  "denopamine",
  "Dental Procedures",
  "Deoxyepinephrine",
  "Derivation procedure",
  "derivatives",
  "Desiccated thyroid",
  "Desipramine",
  "Deslanoside",
  "Detachable balloon",
  "Detection",
  "Device implant NOS",
  "Device therapy",
  "Dexmedetomidine",
  "Dextran",
  "Dexverapamil",
  "Diagnosis",
  "Diagnostic device",
  "Diagnostic test device",
  "Dialysis procedure",
  "Dialysis Solutions",
  "Dialyzers",
  "diastolic augmentation",
  "Diazepam",
  "Dichloroacetate",
  "Diclofenac",
  "Diet, Sodium-Restricted",
  "dietary intervention",
  "Dietary Modification",
  "Dietary restriction NOS",
  "Dietary Supplementation",
  "Digitalis Glycosides",
  "Digitalis preparation",
  "DIGITALIS THERAPY",
  "Digitoxin",
  "Digoxin",
  "DIGOXIN TREATMENT",
  "Dihydralazine",
  "Dihydroergotoxine",
  "dihydropyridine",
  "Dilator",
  "Diltiazem",
  "Dilzem",
  "dimer",
  "Dinoprost",
  "Dinoprostone",
  "Diphosphonates",
  "Dipyridamole",
  "Direct current cardioversion",
  "Discharge Planning",
  "DISCHARGE PROGRAM",
  "Discontinuation",
  "Disease Management",
  "Disease management program",
  "Disks",
  "Disopyramide",
  "Disopyramide Phosphate",
  "Dithiothreitol",
  "Diuretic therapy",
  "Diuretics",
  "Dobutamine",
  "Docosahexaenoic Acids",
  "Documented",
  "dofetilide",
  "donepezil",
  "Dopa",
  "Dopamine",
  "Dopamine Agonists",
  "Dopaminergic Agents",
  "dopexamine",
  "Dopexamine hydrochloride",
  "Double valve replacement",
  "Doxorubicin",
  "DPI 201-106",
  "Drainage procedure",
  "Drug Combinations",
  "Drug Compounding",
  "Drug Delivery Systems",
  "Drug eluting stent",
  "Drugs, Essential",
  "Drugs, Non-Prescription",
  "Dual Chamber",
  "E 1020",
  "E 643",
  "early identification",
  "Early Intervention",
  "Early Mobilization",
  "Echocardiographs",
  "educational intervention",
  "Eicosapentaenoic Acid",
  "Electric Countershock",
  "Electrocardiographic monitoring",
  "Electrocardiographic recorders",
  "Electroconvulsive Therapy",
  "Electrolyte monitoring",
  "Eltroxin",
  "Embolization, Therapeutic",
  "Embryonic Stem Cell Transplantation",
  "Emergency Care",
  "Emergency cesarean section",
  "Emergency medical service",
  "Emergency operation",
  "Emergency procedure",
  "Emergency treatment",
  "Emergency visit",
  "Emotional support",
  "Enalapril",
  "Enalapril Maleate",
  "ENALAPRIL TREATMENT",
  "Enalaprilat",
  "enalkiren",
  "Enbrel",
  "Endocrine therapy",
  "Endothelin receptor antagonist",
  "Enlargement procedure",
  "Eno",
  "Enoximone",
  "Enteral Feeding",
  "Enzyme immunoassay analyzer",
  "enzyme inhibitor therapy",
  "Enzyme Inhibitors",
  "Epicardial lead placement",
  "Epidermal Growth Factor",
  "Epinephrine",
  "Epinine",
  "Epirubicin",
  "eplerenone",
  "Epoetin Alfa",
  "Epoprostenol",
  "eprosartan",
  "Ergometers",
  "Ergometry",
  "erucylphosphocholine",
  "Erythropoietin",
  "Escitalopram",
  "esmolol",
  "Estradiol",
  "Estrogens",
  "Etanercept",
  "Ethanol",
  "Ethmozine",
  "etomoxir",
  "Eucardic",
  "ex vivo perfusion",
  "Exchange Transfusion, Whole Blood",
  "Excision",
  "Excision of muscle NOS",
  "exenatide",
  "Exercise",
  "Exercise, Aerobic",
  "Exercise, Isometric",
  "Experimental drug",
  "Exploration procedure",
  "Expression procedure",
  "Extracorporeal Circulation",
  "Extracorporeal immunoadsorption",
  "Extracorporeal Membrane Oxygenation",
  "Extraction",
  "ezetimibe",
  "Famotidine",
  "Fasidotril",
  "Fatty Acids, Omega-3",
  "FAVOR",
  "febuxostat",
  "FEC protocol",
  "Felodipine",
  "FEMORAL FEMORAL BYPASS",
  "Fenofibrate",
  "Fenoldopam",
  "Fenoldopam Mesylate",
  "Fenoterol",
  "Fetal Therapies",
  "Fiber",
  "Fibrin Tissue Adhesive",
  "Fibrinolytic Agents",
  "Filters",
  "Finding related to non-diagnostic procedure",
  "Finoptin",
  "Fish Oils",
  "Fitness",
  "FK 664",
  "Flecainide",
  "Flecainide Acetate",
  "flosequinan",
  "flosequinoxan",
  "Fluid Management",
  "Fluid monitoring",
  "Fluid restriction",
  "fluorodeoxyglucose",
  "Fluorouracil",
  "fluorouracil/methotrexate protocol",
  "Fluoxetine",
  "Flutamide",
  "Folate",
  "Folic Acid",
  "follow-up",
  "Follow-up visit",
  "Fontan Procedure",
  "Food Supplementation",
  "Forceps",
  "Forecast of outcome",
  "Forskolin",
  "Fosinopril",
  "Fosinopril Sodium",
  "Frame",
  "Free thyroxin",
  "Free triiodothyronine",
  "frumil",
  "Functional behavioral assessment",
  "Furosemide",
  "Gamma Knife Radiosurgery",
  "gamma-glutamyl DOPA",
  "gamma-glutamyl L-dopa",
  "gamma-MSH",
  "Gases",
  "Gelofusin",
  "gemcitabine",
  "Gemtuzumab ozogamicin",
  "gene therapy",
  "Gene Therapy, Somatic",
  "General Anesthesia",
  "Gentamicins",
  "Geriatric Assessment",
  "Glucagon",
  "Glucocorticoids",
  "Glucose",
  "Glucose Control",
  "Glyburide",
  "Glycine",
  "Group Psychotherapy",
  "Guanabenz",
  "guanosine 5'-monophosphorothioate",
  "Guideline Adherence",
  "H 409-22",
  "Hampers",
  "Hawthorn preparation",
  "Health Care",
  "health care utilization",
  "Health education - diet",
  "Health evaluation",
  "Health Insurance",
  "Health Promotion",
  "health risk assessment",
  "Health Services Research",
  "Health Services, National",
  "Heart Arrest, Induced",
  "Heart Bypass, Left",
  "Heart implantation procedure",
  "Heart Transplantation",
  "Heart Valve Prosthesis",
  "Heart, Artificial",
  "Heart-Lung Transplantation",
  "Hemodiafiltration",
  "Hemodilution",
  "Hemodynamic measurements",
  "Hemofiltration",
  "Hemofiltration, Continuous Arteriovenous",
  "Heparin",
  "Herbal supplement",
  "High Ceiling Diuretics",
  "High sodium diet",
  "High-Frequency Ventilation",
  "Histamine H2 Antagonists",
  "History taking",
  "Hoist device",
  "Home Care Services",
  "Home exercise program",
  "HOME HEALTH",
  "Home Nursing",
  "Homograft aortic valve replacement",
  "hormone analog",
  "Hormone precursor",
  "Hormone replacement therapy",
  "Hormones",
  "Hospice Care",
  "Hospital Administration",
  "Hospital admission",
  "Hospital care",
  "HOSPITAL CONSULTATIONS",
  "Hospital Readmissions",
  "Hospitalization",
  "House Call",
  "Human B-type natriuretic peptide",
  "Human plasma",
  "Hydralazine",
  "Hydralazine Hydrochloride",
  "hydrochloride",
  "Hydrochlorothiazide",
  "hydrochlorothiazide-triamterene",
  "Hydrocortisone",
  "Hydroflumethiazide",
  "Hydrostat",
  "Hydrotherapy",
  "Hydroxymethylglutaryl-CoA Reductase Inhibitors",
  "hyperbaric oxygen",
  "Hyperbaric Oxygenation",
  "HYPERTENSION MEDICATION",
  "Hypertonic Solutions",
  "hypothermia, induced",
  "ibopamine",
  "Ibuprofen",
  "ibutilide",
  "ICI 153110",
  "ICI 170777",
  "Iloprost",
  "Imaging Device",
  "Imaging Services",
  "Imaging Techniques",
  "imatinib",
  "imidapril",
  "Imidazole",
  "imidazole mustard",
  "imidazoline receptor agonist",
  "Imipramine",
  "Immune Sera",
  "Immunoglobulins",
  "Immunoglobulins, Intravenous",
  "Immunotherapy",
  "Impedance Cardiographs",
  "Implantable Pump",
  "Implantation of left ventricular assist device",
  "Implantation of ventricular assist device",
  "Implantation procedure",
  "Implants",
  "Impromidine",
  "In situ perfusion",
  "Inamrinone",
  "Incision and drainage",
  "Incision of sternum",
  "Incretin",
  "Indapamide",
  "Individual psychotherapy",
  "indole-3-carbinol",
  "Indomethacin",
  "Indoramin",
  "Induced diuresis",
  "Induced Hyperthermia",
  "Induced hypotension",
  "Induced vasodilatation",
  "Induction",
  "Induction of neuromuscular blockade",
  "Inflammation Mediators",
  "Inflation procedure",
  "infliximab",
  "Influenza vaccination",
  "Influenza virus vaccine",
  "Information Systems, Telemedicine",
  "Infrared radiation therapy",
  "Infusion procedures",
  "Infusion Pump",
  "Inhalation Therapy",
  "Inhaled terbutaline",
  "inhibitors",
  "Injection procedure",
  "Injection therapy",
  "Innovative Therapies",
  "Inocor",
  "Inotropic agent",
  "Insertion of endocardial electrode for temporary cardiac pacing",
  "Inspiratory muscle training",
  "Inspra",
  "Institutional care",
  "Insulin",
  "INSULIN TREATMENT",
  "Insulin-Like Growth Factor I",
  "Insulin-Like Growth Factor II",
  "Intact parathyrin",
  "INTEGRATOR",
  "intensive care",
  "Interferon Alfa-2b",
  "Interferon-beta",
  "Interleukins",
  "Intermittent administration",
  "Intermittent hemofiltration",
  "Intermittent Positive-Pressure Ventilation",
  "intervention program",
  "Intervention regimes",
  "Intra-aortic balloon pump device",
  "Intra-Aortic Balloon Pumping",
  "Intra-Arterial Infusions",
  "INTRAVENOUS DRUG",
  "Intravenous infusion procedures",
  "Intravenous therapy",
  "Intravenous vasodilator",
  "Introduction procedure",
  "Intubation",
  "Intubation, Intratracheal",
  "invasive treatment",
  "investigation",
  "Iontophoresis",
  "ipazilide fumarate",
  "irbesartan",
  "Irinotecan hydrochloride",
  "Iron",
  "iron chelation therapy",
  "Ischemic Preconditioning",
  "Isoflurane",
  "isomazole",
  "Isoproterenol",
  "Isosorbide Dinitrate",
  "isosorbide dinitrate-hydralazine combination",
  "Isosorbide Mononitrate",
  "Isotonic exercise",
  "Isradipine",
  "itavastatin",
  "ivabradine",
  "JTV519",
  "K-Strophanthidin",
  "Kallidin",
  "Ketanserin",
  "KIDNEY EXTRACT",
  "Kidney Transplantation",
  "kinase inhibitor",
  "Kininogenase",
  "KW 3902",
  "L 158809",
  "Labetalol",
  "lacidipine",
  "Lactate",
  "Lactated Ringer's Solution",
  "Lactulose",
  "landiolol",
  "Lanoxicaps",
  "Laparoscopic fundoplication",
  "Laser Therapy, Low-Level",
  "Lead compound",
  "Leads",
  "Left ventricular assist device",
  "Leptin",
  "Leukotriene Antagonists",
  "Levocarnitine",
  "Levodopa",
  "Levosimendan",
  "Lidocaine",
  "Life Support Care",
  "Life support procedure",
  "Life Sustaining Treatment",
  "Lifesaving",
  "Ligation",
  "Ligation of artery",
  "Ligation of patent ductus arteriosus",
  "Ligature",
  "Light Exercise",
  "Lipid-lowering therapy",
  "Liposomal Doxorubicin",
  "Lisinopril",
  "Lithium",
  "Lithium Carbonate",
  "Lithium therapy",
  "Local perfusion of kidney",
  "long-term care",
  "Loop Diuretics",
  "Loops",
  "Losartan",
  "low sodium",
  "Lower Body Negative Pressure",
  "LU 135252",
  "Lung Transplantation",
  "Luteolin",
  "lycopene",
  "magnesium orotate",
  "Magnesium supplement",
  "Magnesium supplementation",
  "Magnetic Resonance Imaging",
  "Maintenance therapy",
  "major surgery",
  "Managed Care",
  "Management procedure",
  "Mandibular right first molar abutment",
  "Manipulation procedure",
  "Mannitol",
  "Manual expression",
  "Manual lymphatic drainage",
  "Markers, Bone",
  "Matrix Metalloproteinase Inhibitor",
  "MAV protocol",
  "Maxillary right first molar abutment",
  "MCC 135",
  "MCC protocol",
  "MCI 154",
  "MDL 19,205",
  "MDL-17,043",
  "Mechanical assistance",
  "Mechanical ventilation",
  "Median sternotomy",
  "medical appointment",
  "Medical Devices",
  "Medical service",
  "Medical therapy",
  "Medicament",
  "Medication Management",
  "Medications, cardiovascular",
  "Medigoxin",
  "Melatonin",
  "Mesenchymal Stem Cell Transplantation",
  "Metabolic therapy",
  "Metformin",
  "Methacholine",
  "Methandrostenolone",
  "Methimazole",
  "Methoxamine",
  "Methyldigoxin",
  "Metoclopramide",
  "Metolazone",
  "Metoprolol",
  "metoprolol succinate",
  "Metoprolol Tartrate",
  "Metric",
  "Mexiletine",
  "Mibefradil",
  "Microinjections",
  "Microscopes, Electron",
  "Microscopes, Electron, Scanning",
  "Midazolam",
  "Midodrine",
  "Milrinone",
  "Minipress",
  "Minoxidil",
  "Mitogens",
  "Mitoxantrone",
  "Mitral valve replacement NOS",
  "MK-422",
  "MK-521",
  "Moderate Exercise",
  "Moduretic",
  "Molecular Target",
  "Molsidomine",
  "Monensin",
  "Monitoring Device",
  "Monitoring Systems",
  "Monitoring, Physiologic",
  "Monitors, Environmental, Chemical Agent",
  "Monoplace Hyperbaric Chambers",
  "Moricizine",
  "Morphine",
  "Motivating patient",
  "moxonidine",
  "Multivitamin preparation",
  "Muscle stimulant",
  "Muzolimine",
  "Myocardial Reperfusion",
  "Myocardial Revascularization",
  "N,N'-dipyridoxylethylenediamine-N,N'-diacetic acid",
  "N,N-dimethylarginine",
  "N-3 fatty acid supplementation",
  "N-n-propyl-N-n-butyl-beta-dopamine",
  "N-terminal pro-B-type natriuretic peptide",
  "Naloxone",
  "nanterinone",
  "Naproxen",
  "Nasal Continuous Positive Airway Pressure",
  "Natrecor",
  "Natriuretic Hormones",
  "Natriuretic Peptides",
  "nebivolol",
  "Neostigmine",
  "Nephrectomy",
  "Neurohormones",
  "Neurology service",
  "Neuromuscular stimulation",
  "Neurostimulation procedures of spinal cord tissue",
  "Nicardipine",
  "Nicergoline",
  "Nicorandil",
  "Nicotine",
  "Nicotinic Agonists",
  "Nifangin",
  "Nifedipine",
  "nimesulide",
  "Nipruton",
  "Nisoldipine",
  "Nitrate compound therapy",
  "Nitrates",
  "Nitrendipine",
  "Nitric Oxide Donors",
  "nitric oxide receptor",
  "Nitric Oxide Synthase Inhibitors",
  "Nitric oxide therapy",
  "Nitrites",
  "Nitroglycerin",
  "Nitroprusside",
  "Nitrosorbide",
  "nitroxyl",
  "Nizatidine",
  "NKH 477",
  "NMDA receptor antagonist",
  "Norepinephrine",
  "Normal saline",
  "Notifications NOS",
  "NSP 805",
  "Nursing Diagnoses",
  "Nursing interventions",
  "Nursing Process",
  "Nutritional Support",
  "Obstetric Delivery",
  "Occluders",
  "Octreotide",
  "Office Visits",
  "Oils, Volatile",
  "olmesartan",
  "olprinone",
  "Olympic Games",
  "omapatrilat",
  "Omega-3 Acid Ethyl Esters",
  "Ondansetron",
  "ONO 41483",
  "OPC 18790",
  "OPC 31260",
  "OPC 8212",
  "Open approach",
  "Open heart surgery",
  "Operation on fetus",
  "Operative procedure on coronary arteries",
  "Operative Surgical Procedures",
  "Opiates",
  "Oral anticoagulants",
  "Oral form digoxin",
  "Oral form furosemide",
  "Oral medication",
  "Oral supplement",
  "ORALIT",
  "Organ Donation procedure",
  "Organ Transplantation",
  "Ouabain",
  "Ovariectomy",
  "oxaprozin",
  "Oxygen",
  "Oxygen Therapy Care",
  "oxymatrine",
  "Oxypurinol",
  "PACEMAKER PERMANENT",
  "Pacemakers",
  "Pacemakers, Cardiac, Implantable, Resynchronization",
  "Paclitaxel",
  "Pain management",
  "Palliative Care",
  "Palliative Surgery",
  "PAMP(1-20)NH2",
  "para-trifluoro-methyl-5-phenyl-1,2,4-oxadiazole",
  "parathyroid hormone-related protein",
  "Parathyroidectomy",
  "parecoxib",
  "parenteral administration",
  "Parenteral therapy",
  "paricalcitol",
  "Partial sternotomy",
  "Partial ventriculectomy",
  "particle",
  "Passive exercise NOS",
  "Patient Admission",
  "patient assessment",
  "patient care",
  "Patient chart",
  "Patient Discharge",
  "Patient History",
  "Patient identification",
  "Patient Monitoring",
  "Patient Participation",
  "PATIENT PROFILE",
  "Patient Readmission",
  "Patient referral",
  "Patient Selection",
  "Patient Transport",
  "Patient-Centered Care",
  "peer prevention",
  "PEG-3350",
  "pentaacetylgitoxin",
  "Pentaerythritol Tetranitrate",
  "pentosidine",
  "Pentoxifylline",
  "peptide hormone",
  "Peptidyl-Dipeptidase A",
  "Percocet",
  "Percutaneous coronary intervention",
  "Percutaneous needle biopsy",
  "Percutaneous valvuloplasty",
  "Perhexiline",
  "Pericardiectomy",
  "Pericardiotomy",
  "Perindopril",
  "Perindopril Erbumine",
  "perindoprilat",
  "Peripheral Stem Cell Transplantation",
  "Peripheral vasodilators",
  "Peritoneal Dialysis",
  "Peritoneal Dialysis, Continuous Ambulatory",
  "Pharmaceutical Preparations",
  "Pharmaceutical Services",
  "Pharmacologic Substance",
  "Pharmacological Treatment",
  "Pharmacotherapy",
  "Phentolamine",
  "PHENYL",
  "Phenylephrine",
  "Phenytoin",
  "Phosphocreatine",
  "Phosphodiesterase 5 inhibitor",
  "Phosphodiesterase Inhibitors",
  "Photochemotherapy",
  "Phototherapy",
  "Physical activity",
  "Physical Examination",
  "PHYSICAL PERFORMANCE",
  "Physical therapy",
  "Physical therapy exercises",
  "Physician support",
  "Physiologic monitoring system",
  "Phytotherapy",
  "pimagedine",
  "pimobendan",
  "Pindolol",
  "pioglitazone",
  "pirbuterol",
  "piretanide",
  "pirfenidone",
  "piroximone",
  "Placebos",
  "Plasma Exchange",
  "Plastic operation on muscle",
  "Plastic repair of aortic valve NOS",
  "Plastic Surgical Procedures",
  "Pleurodesis",
  "Plication",
  "PN 200-110",
  "Pneumococcal vaccine",
  "Polypharmacy",
  "Positive inotropic drug",
  "Positive pressure therapy",
  "Positive-Pressure Respiration",
  "Postoperative Care",
  "Potassium Chloride",
  "Potassium Sparing Diuretics",
  "Potassium supplement",
  "PPET",
  "prasugrel",
  "Pravastatin",
  "Prazosin",
  "Prazosin hydrochloride",
  "prednisolone",
  "Prednisone",
  "prednylidene",
  "Prenalterol",
  "prenatal therapy",
  "Preoperative Care",
  "Prescription of prophylactic anticoagulant",
  "prescription procedure",
  "Prescriptions, Drug",
  "Pressors",
  "Pressure support",
  "Pressure support ventilator",
  "Prevention",
  "prevention of disorder",
  "Primary Health Care",
  "Primary Prevention",
  "proadrenomedullin",
  "Probes",
  "Problem solving therapy",
  "Probucol",
  "Procainamide",
  "Procedure on heart",
  "Procedure on spinal cord",
  "Procedures",
  "Propafenone",
  "Prophylactic treatment",
  "propionylcarnitine",
  "Propranolol",
  "PROPRANOLOL TREATMENT",
  "Propyl Gallate",
  "Propylthiouracil",
  "prostaglandin A1",
  "prostaglandin inhibition",
  "Prostaglandins",
  "Prosthesis",
  "Protease Inhibitor",
  "Protein Arrays",
  "Protein Kinase C Inhibitor",
  "Protein-tyrosine kinase inhibitor",
  "Proton Pump Inhibitors",
  "PST 2238",
  "Psychotherapy",
  "Psychotherapy, Multiple",
  "PTH protein, human",
  "Pulmonary Artery Catheterization",
  "Pulmonary artery pressure monitoring",
  "Pulmonary valvotomy",
  "Pulse Generators",
  "pump",
  "Pumps, Blood",
  "Punch",
  "Puncture procedure",
  "Pycnogenol",
  "Pyridostigmine",
  "Pyridostigmine Bromide",
  "Pyridoxal Phosphate",
  "quinapril",
  "Quinapril hydrochloride",
  "Quinidine",
  "Quinidine Sulfate",
  "Quinuclidinyl Benzilate",
  "Radiation therapy",
  "Radicals",
  "Radiosurgery",
  "Ramipril",
  "ramiprilat",
  "ranolazine",
  "Reading",
  "Reality Therapy",
  "Rebreathing method",
  "Recombinant Erythropoietin",
  "Recombinant Growth Hormone",
  "Recombinant Interferon-gamma",
  "recombinant peptide",
  "Reconstructive Surgical Procedures",
  "Registration",
  "Rehabilitation therapy",
  "Rehabilitation, physical",
  "Relaxation",
  "Relaxin",
  "Removal of endotracheal tube",
  "Renal Replacement Therapy",
  "Renin-angiotensin-aldosterone System Inhibitors",
  "Renitec",
  "Repair of aneurysm by endoaneurysmoplasty",
  "Repair of aneurysm of abdominal aorta",
  "Reparative closure",
  "Repeat Surgery",
  "Reperfusion Therapy",
  "Replacement therapy",
  "Reporting",
  "Repositioning",
  "resistance education",
  "resistin",
  "Respiration, Artificial",
  "Respiratory gas monitoring",
  "Respiratory Therapy",
  "Rest",
  "Resuscitation",
  "resveratrol",
  "retransplantation",
  "Retrospective audit",
  "Revascularization - action",
  "RG W-2938",
  "Rhythmical exercises",
  "Riboflavin",
  "Right hemicolectomy",
  "Ring device",
  "Risk Assessment",
  "Risk Management",
  "Risk Reduction",
  "rituximab",
  "Ro 13-6438",
  "Ro 40-5967",
  "rofecoxib",
  "Rolls",
  "rosiglitazone",
  "rosuvastatin",
  "Routine procedure",
  "roxatidine",
  "Running",
  "Safety precautions",
  "salicylate",
  "Salicylic Acid",
  "Saline Solution, Hypertonic",
  "salmeterol",
  "saluretic",
  "Salvage procedure",
  "Salvage Therapy",
  "sampatrilat",
  "Sanofi Winthrop",
  "sarpogrelate",
  "saterinone",
  "Sch 34826",
  "Scopolamine",
  "Screening mammography",
  "Screening procedure",
  "Screening Tests",
  "Screens",
  "Secondary prevention",
  "Selective Angiotensin II Receptor Antagonists",
  "Selegiline",
  "Self Care",
  "Self Monitoring",
  "Self-Management",
  "sematilide",
  "Sensors",
  "Serotonin Antagonists",
  "Serotonin Uptake Inhibitors",
  "Sertraline",
  "Serum cortisol",
  "sevoflurane",
  "Sex Counseling",
  "SGB 1534",
  "Shunt Device",
  "sildenafil",
  "Sildenafil citrate",
  "simendan",
  "Simvastatin",
  "sinomenine",
  "SK&F 94836",
  "SK&F 95654",
  "Skeletal Muscle Ventricle",
  "skeletal transplantation",
  "Sky-diving",
  "Sleep Treatment",
  "Sodium Chloride",
  "Sodium Dichloroacetate",
  "Sodium diet",
  "Sodium Nitroprusside",
  "sodium phosphate",
  "Sodium salts",
  "Somatomedins",
  "Somatotropin",
  "Somatropin",
  "Sotalol",
  "Sounds device",
  "Spinal instrumentation",
  "spirapril",
  "Spiritual support",
  "Spirometer",
  "Spironolactone",
  "Spironolactone+furosemide",
  "Splint Device",
  "split brain",
  "Sports",
  "SQ 28603",
  "SQ-14,225",
  "Stabilization",
  "Stellate ganglion block",
  "stem cell therapy",
  "Stem cell transplant",
  "Stent/Grafts, Vascular, Coronary",
  "Sterically Stabilized Liposome",
  "Steroid therapy",
  "Stimulant",
  "Stimulation procedure",
  "Stimulator",
  "Streptokinase",
  "Streptozocin",
  "Stress management",
  "Stroke prevention",
  "strophanthin K",
  "subcutaneous application",
  "Subcutaneous heparin",
  "Substitution therapy",
  "succinate",
  "Succinylcholine",
  "Sugars",
  "Sulfides",
  "Sulfonylurea Compounds",
  "Sulindac",
  "sulmazole",
  "Superoxide Dismutase",
  "Supervision",
  "Supplementation",
  "Support, device",
  "Supportive care",
  "Surgical Management",
  "Surgical Manipulation",
  "Surgical Procedures, Elective",
  "Surgical repair",
  "Surgical Replantation",
  "Surgical sequestration",
  "Surgical sutures",
  "Sustained exercise",
  "Swan-Ganz catheter, device",
  "Sympathectomy",
  "Sympatholytics",
  "Sympathomimetics",
  "Symptom control",
  "Symptom Management",
  "Synthetic drug",
  "T 0201",
  "Tace",
  "Tai Ji",
  "Taking medication",
  "Task Performance",
  "Taurine",
  "Taxol",
  "TCV 116",
  "technetium Tc 99m 1,2-bis(bis(2-ethoxyethyl)phosphino)ethane",
  "tedisamil",
  "Telehealth",
  "Telemedicine",
  "Telephone consultation",
  "telmisartan",
  "Temporary artificial heart prosthesis",
  "Tenecteplase",
  "Teprotide",
  "terazosine",
  "Terbutaline",
  "terminal patient care",
  "Termination of pregnancy",
  "tertiary prevention",
  "Testosterone",
  "Tetradecanoylphorbol Acetate",
  "Tetraethylammonium",
  "tetramethylpyrazine",
  "tezosentan",
  "Thalidomide",
  "The science and art of healing",
  "Theophylline",
  "Therapeutic agent",
  "Therapeutic Effect",
  "Therapeutic heat application",
  "Therapeutic immunosuppression",
  "Therapeutic Intervention",
  "Therapeutic procedure",
  "Therapeutic Processes",
  "Therapeutic regimen",
  "therapeutic use",
  "Therapies, Investigational",
  "Thermal techniques",
  "Thiamine",
  "Thiamine Pyrophosphate",
  "Thiazide Diuretics",
  "Thiazides",
  "Thiazolidinediones",
  "Thioxanthenes",
  "Thoracentesis",
  "Thoracic Surgical Procedures",
  "Thoracotomy",
  "Thrombectomy",
  "Thrombin",
  "Thrombolytic Therapy",
  "Thyroid Hormones",
  "Thyrotropin",
  "Thyroxine",
  "Tissue Engineering",
  "Tissue Inhibitor of Metalloproteinases",
  "Tissue Transplantation",
  "TNFR-Fc fusion protein",
  "tocilizumab",
  "ToMORROW",
  "Tonics",
  "torborinone",
  "torsemide",
  "Tourniquets, Pneumatic, Automatic Rotating",
  "Tracheotomy procedure",
  "Tramadol",
  "trandolapril",
  "Transdermal glyceryl trinitrate",
  "Transducers",
  "Transducers, Pressure",
  "Transesophageal cardiac pacing procedure",
  "Transjugular intrahepatic portosystemic shunt procedure",
  "Transplantation",
  "Transplantation of liver",
  "Transplantation, Autologous",
  "Transplantation, Heterotopic",
  "Trapidil",
  "trastuzumab",
  "Treadmill",
  "Treatment Guidelines",
  "treatment method",
  "treatment program",
  "Treatment Protocols",
  "Tretinoin",
  "Triage",
  "Triamterene",
  "Triethylenetetramine",
  "Triiodothyronine",
  "trimazosin",
  "Trimetazidine",
  "Triple valve replacement",
  "tumor necrosis factor therapy",
  "Tumor Necrosis Factor-alpha",
  "Tylosin",
  "Tyramine",
  "TZC 5665",
  "Ubiquinone",
  "UD CG 212 Cl",
  "UK 79300",
  "Ultrafiltration",
  "Unithiol",
  "urapidil",
  "urocortin",
  "Urotensins",
  "Vaccination",
  "Vagotomy",
  "valsartan",
  "Vancomycin",
  "vardenafil",
  "VASCULAR ACCESS",
  "vasoactive agent",
  "Vasoactive Intestinal Peptide",
  "Vasoconstrictor Agents",
  "Vasodilator Agents",
  "Vasopressin Antagonist",
  "Vastarel",
  "venlafaxine",
  "Venous blood sampling",
  "Ventricular assist device",
  "Ventricular puncture",
  "VENTRICULOTOMY",
  "Verapamil",
  "vesnarinone",
  "Viagra",
  "viprostol",
  "Viral Vector",
  "Visit, hospital",
  "Visit, outpatient",
  "Vitamin A",
  "Vitamin B Complex",
  "Vitamin B6",
  "Vitamin D",
  "Vitamin E",
  "Vitamin supplementation",
  "vitamin therapy",
  "Vitamins",
  "Volume control",
  "von Willebrand Factor",
  "Walking",
  "Warfarin",
  "Warming/Cooling Units, Patient",
  "Water",
  "Weight maintenance regimen",
  "Weight monitoring",
  "Win-47203",
  "Wincoram",
  "Xamoterol",
  "Xamtol",
  "Xanthine Oxidase Inhibitors",
  "Xenobiotics",
  "Xenograft procedure",
  "YM 087",
  "Young's cardioplegic solution",
  "Zinc",
  "ziprasidone",
  "zofenopril",
  "ZOFENOPRIL CALCIUM",
  "Zonal",
  "{PROVIDER}"
]

# ATRI_FIB_TREATMENTS = [
#   '-plasty',
#   '2-aminofluorene',
#   '3-Iodobenzylguanidine',
#   'Ablation',
#   'Ablation Catheters',
#   'Acenocoumarol',
#   'acetovanillone',
#   'Acupuncture procedure',
#   'Adenosine',
#   'Adenosine Diphosphate Receptor Inhibitors',
#   'Adjustment Action',
#   'adjuvant therapy',
#   'Administration, Oral',
#   'Adrenal Cortex Hormones',
#   'Adrenergic beta-Antagonists',
#   'Advice',
#   'Ajmaline',
#   'Albuterol',
#   'Aldosterone',
#   'Aldosterone Antagonists',
#   'Aldosterone Receptor Antagonists',
#   'Alteplase',
#   'Alternative Therapies',
#   'amidronate',
#   'Aminophylline',
#   'Amiodarone',
#   'Amiodarone hydrochloride',
#   'Amlodipine',
#   'Amputation',
#   'Anesthesia procedures',
#   'Anesthesia, Epidural',
#   'Angiopoietin-2',
#   'Angiotensin II',
#   'Angiotensin II receptor antagonist',
#   'Angiotensin II Type 1 Receptor Blockers',
#   'Angiotensin-Converting Enzyme Inhibitors',
#   'Angiotensins',
#   'Annuloplasty',
#   'Anti-Anxiety Agents',
#   'Anti-Arrhythmia Agents',
#   'Anti-Bacterial Agents',
#   'Anti-Inflammatory Agents',
#   'Anti-Inflammatory Agents, Non-Steroidal',
#   'Antibiotics',
#   'Anticoagulant drug monitoring',
#   'Anticoagulant therapy',
#   'Anticoagulants',
#   'anticoagulation',
#   'ANTICOAGULATION TREATMENT',
#   'Antidepressive Agents',
#   'Antifibrinolytic Agents',
#   'Antihypertensive Agents',
#   'Antihypertensive therapy',
#   'Antiinflammatory therapy',
#   'Antioxidants',
#   'Antiplatelet Agents',
#   'Antiplatelet therapy',
#   'Antithrombin III',
#   'aortic balloon pump',
#   'Aortic valve replacement NOS',
#   'Application procedure',
#   'Aprindine',
#   'Arsenal',
#   'Arteriovenous graft',
#   'Arthroplasty',
#   'Arthroplasty, Replacement, Hip',
#   'Arthroplasty, Replacement, Knee',
#   'Ascorbic Acid',
#   'asparaginase/prednisone/vincristine protocol',
#   'Aspirin',
#   'Assessment procedure',
#   'Atenolol',
#   'atorvastatin',
#   'Atrial cardioversion',
#   'Atrial operation',
#   'Atrial overdrive pacing',
#   'Atropine',
#   'Autologous Stem Cell Transplantation',
#   'Autonomic Denervation',
#   'azimilide',
#   'azimilide dihydrochloride',
#   'Balloon Dilatation',
#   'Balloon dilatation catheter',
#   'Balloon mitral valvotomy',
#   'Balloon Occlusion',
#   'Balloon Valvuloplasty',
#   'Bands',
#   'benazepril',
#   'Bepridil',
#   'Bepridil hydrochloride',
#   'Beta blocker prophylaxis',
#   'BETA BLOCKER TREATMENT',
#   'Betapace AF',
#   'Betaxolol',
#   'bidisomide',
#   'Biological Response Modifier Therapy',
#   'Biomedical Monitors',
#   'Bisoprolol',
#   'Blood Pressure Monitors',
#   'Boards',
#   'Bone plates',
#   'Bone Wires',
#   'Booster',
#   'Brain natriuretic peptide',
#   'Bretylium Tosylate',
#   'bucindolol',
#   'Butorphanol Tartrate',
#   'Bypass',
#   'Bypass graft',
#   'Bypass surgery',
#   'Caffeine',
#   'Calcium Channel Blockers',
#   'candesartan',
#   'candesartan cilexetil',
#   'Cannulation',
#   'capecitabine',
#   'Cardiac ablation',
#   'Cardiac Glycosides',
#   'Cardiac Monitors',
#   'Cardiac pacing NOS',
#   'Cardiac rehabilitation',
#   'Cardiac resynchronisation therapy',
#   'Cardiac Stimulators',
#   'Cardiac Surgery procedures',
#   'Cardiopulmonary Bypass',
#   'Cardiovascular Agents',
#   'Cardiovascular Surgical Procedures',
#   'Carotid sinus massage',
#   'carvedilol',
#   'Catheter Ablation, Percutaneous',
#   'Catheter Ablation, Radiofrequency',
#   'Catheter Ablation, Transvenous',
#   'catheter device',
#   'catheter management',
#   'Catheter procedure',
#   'Catheterization',
#   'Catheters, Cardiac, Ablation',
#   'Catheters, Electrode',
#   'Catheters, Vascular, Retrieval, Basket',
#   'Cell hybridization',
#   'Cell Therapy',
#   'Central venous catheter',
#   'certoparin',
#   'Channel Blockers',
#   'Charts',
#   'chemosensitization/potentiation',
#   'chronic anticoagulation',
#   'cifenline',
#   'Cigarette Smoking',
#   'Cilazapril',
#   'cilostazol',
#   'cisplatin/cyclophosphamide/doxorubicin/etoposide chemotherapy protocol',
#   'Clamp',
#   'Class Ia antiarrhythmic drug',
#   'Class Ic antiarrhythmic drug',
#   'Class III antiarrhythmic drug',
#   'Clinical Management',
#   'Clinical Treatment',
#   'Clipping',
#   'Clonidine',
#   'clopidogrel',
#   'Closure of defect of interatrial septum NOS',
#   'Coagulants',
#   'Coagulation procedure',
#   'Cold Therapy',
#   'Combined Modality Therapy',
#   'Complete excision',
#   'Complex procedure',
#   'Conscious Sedation',
#   'Conservative therapy',
#   'Continuous ECG monitoring',
#   'Continuous Intravenous Infusion',
#   'Continuous Positive Airway Pressure',
#   'Conventional Surgery',
#   'Convulsive therapy',
#   'Cordarone',
#   'Coronary Artery Bypass Surgery',
#   'Coronary revascularisation',
#   'Corridor operation',
#   'Coumadin',
#   'coumarin',
#   'Coumarins',
#   'Counseling',
#   'Covers',
#   'Cox-maze procedure',
#   'CRT-D',
#   'Cryosurgery',
#   'Curative Surgery',
#   'cytarabine/daunorubicin protocol',
#   'Cytokine therapy',
#   'Dalteparin',
#   'DC shock',
#   'DEFIBRILLATOR, IMPLANTABLE, DUAL-CHAMBER',
#   'Defibrillators',
#   'Defibrillators, Implantable',
#   'DELIVER',
#   'Denervation',
#   'Detection',
#   'Device therapy',
#   'Dexverapamil',
#   'Diagnosis',
#   'Diagnostic device',
#   'Dialysis procedure',
#   'Diethylstilbestrol',
#   'digitalin',
#   'Digitalis Glycosides',
#   'Digitalis preparation',
#   'DIGITALIS THERAPY',
#   'Digoxin',
#   'DIGOXIN TREATMENT',
#   'dihydropyridine',
#   'Diltiazem',
#   'Dimethoxyamphetamine',
#   'Diphosphonates',
#   'Direct current cardioversion',
#   'Direct current therapy',
#   'Direct thrombin inhibitor',
#   'DISCHARGE PROGRAM',
#   'Discontinuation',
#   'Disease Management',
#   'Disopyramide',
#   'Dissection',
#   'Diuretics',
#   'Diversion procedure',
#   'Division',
#   'Dobutamine',
#   'docetaxel',
#   'Docosahexaenoic Acids',
#   'Documented',
#   'dofetilide',
#   'Double valve replacement',
#   'Drainage procedure',
#   'dronedarone',
#   'Drug eluting stent',
#   'Drug Infusion Systems',
#   'Drug Monitoring',
#   'Drugs, Investigational',
#   'Dual Chamber',
#   'E-Therapy',
#   'early identification',
#   'Early Mobilization',
#   'Echocardiographs',
#   'Echocardiography',
#   'educational intervention',
#   'Eicosapentaenoic Acid',
#   'Elective electrical cardioversion of arrhythmia, external',
#   'Elective procedure',
#   'Electric Countershock',
#   'Electric Stimulation Therapy',
#   'Electroanatomical Mapping Systems',
#   'Electrocardiographic monitoring',
#   'Electrocardiographic recorders',
#   'Electrolyte replacement',
#   'Embolectomy',
#   'Embolization, Therapeutic',
#   'Emergency CABG',
#   'Emergency Care',
#   'Emergency medical service',
#   'Emergency visit',
#   'Empirical therapy',
#   'Enalapril',
#   'Encainide',
#   'Endarterectomy, Carotid',
#   'Endocrine therapy',
#   'Enoxaparin',
#   'eplerenone',
#   'Epoprostenol',
#   'Erythrocyte Transfusion',
#   'Erythromycin',
#   'esmolol',
#   'Esophagectomy',
#   'Ethanol',
#   'Excision',
#   'Excision of muscle NOS',
#   'Exercise',
#   'Exercise, Isometric',
#   'Exploration procedure',
#   'Expression procedure',
#   'Extraction',
#   'Extrapleural pneumonectomy',
#   'ezetimibe',
#   'Factor VIII',
#   'Falepsin',
#   'Fatty Acids, Omega-3',
#   'FAVOR',
#   'Fibrinolytic Agents',
#   'Fish Oils',
#   'Flecainide',
#   'Flecainide Acetate',
#   'flestolol',
#   'flosequinan',
#   'fluorophore',
#   'follow-up',
#   'fondaparinux',
#   'Forecast of outcome',
#   'Formation of pericardial baffle, interatrial',
#   'fragmentation procedure',
#   'Frame',
#   'Gallopamil',
#   'General Anesthesia',
#   'geranylgeranylacetone',
#   'Glucose',
#   'Glycerol',
#   'Group Psychotherapy',
#   'Guideline Adherence',
#   'HA 7',
#   'Handball',
#   'Health Care',
#   'Heart Arrest, Induced',
#   'HEART RATE TARGET',
#   'Heart Transplantation',
#   'Heart Valve Prosthesis',
#   'Heart valve replacement',
#   'HEART-VALVE, MECHANICAL',
#   'Heparin',
#   'Heparin, Low-Molecular-Weight',
#   'High frequency ablation',
#   'Hospital Administration',
#   'Hospital admission',
#   'Hospital Readmissions',
#   'Hospitalization',
#   'Hydralazine',
#   'hydrochloride',
#   'hydroquinidine',
#   'Hydroxymethylglutaryl-CoA Reductase Inhibitors',
#   'ibutilide',
#   'Illicit Drugs',
#   'Imaging Techniques',
#   'Immobilization',
#   'Implant, pacemaker',
#   'Implantation procedure',
#   'Implants',
#   'Incision and drainage',
#   'Incision of sternum',
#   'Individual psychotherapy',
#   'indobufen',
#   'Induction',
#   'Indwelling Catheter',
#   'Inferential Current Treatment',
#   'Inflation procedure',
#   'Infusion procedures',
#   'Injection procedure',
#   'Inotropic agent',
#   'Insulin',
#   'Insurance, Long-Term Care',
#   'Internal cardioversion',
#   'Intervention regimes',
#   'Intra-aortic balloon pump device',
#   'Intra-Aortic Balloon Pumping',
#   'Intravenous sedation',
#   'Intravenous therapy',
#   'Introduction procedure',
#   'invasive treatment',
#   'investigation',
#   'Iodine',
#   'Ion Channel',
#   'Iontophoresis',
#   'irbesartan',
#   'Ischemic Preconditioning',
#   'Isolation procedure',
#   'Isoproterenol',
#   'Isotonic exercise',
#   'Kinilentin',
#   'Kordaron',
#   'landiolol',
#   'Leads',
#   'Lidocaine',
#   'Lidoflazine',
#   'Lifestyle counseling',
#   'Ligation',
#   'Lipid-lowering therapy',
#   'Lobectomy',
#   'long-term care',
#   'Long-term drug therapy',
#   'Longterm Follow-up',
#   'Losartan',
#   'Magnesium',
#   'Magnesium Sulfate',
#   'Magnetocardiographs',
#   'Maintenance therapy',
#   'Managed Care',
#   'Management procedure',
#   'Maze operation',
#   'Mechanical ventilation',
#   'Medical therapy',
#   'Medication Management',
#   'Medications, blood',
#   'Medications, cardiovascular',
#   'melagatran',
#   'Mercury sphygmomanometer',
#   'Metoprolol',
#   'metoprolol succinate',
#   'Metric',
#   'Metyrapone',
#   'Mexiletine',
#   'Mibefradil',
#   'Microelectrodes',
#   'Mitral valve operation',
#   'Mitral valve prosthesis',
#   'Mitral valve replacement NOS',
#   'Mitral valvotomy',
#   'Monitoring Device',
#   'Monitoring Systems',
#   'Moricizine',
#   'N,N-dimethylarginine',
#   'Nafarelin',
#   'National Hospital Discharge Survey',
#   'nebivolol',
#   'Nebulizers',
#   'Neuromuscular Blocking Agents',
#   'Neurostimulation procedures of spinal cord tissue',
#   'nibentan',
#   'Nifedipine',
#   'NIP142',
#   'Non-cardioselective beta-blocker',
#   'Norepinephrine',
#   'Notifications NOS',
#   'Novocainamide',
#   'Occluders',
#   'Open approach',
#   'Open heart surgery',
#   'Operative procedure on coronary arteries',
#   'Operative Surgical Procedures',
#   'Opium',
#   'Opportunistic screening',
#   'Oral anticoagulants',
#   'Oral form verapamil',
#   'Oral medication',
#   'ORALIT',
#   'Ouabain',
#   'Outpatient procedure',
#   'p-Aminosalicylic Acid',
#   'PACEMAKER PERMANENT',
#   'Pacemakers',
#   'Pacerone',
#   'Pads',
#   'Pain management',
#   'Palliative Care',
#   'Palliative procedure',
#   'patient care',
#   'Patient Care Management',
#   'Patient Discharge',
#   'Patient History',
#   'Patient identification',
#   'Patient Isolation',
#   'Patient Selection',
#   'Percutaneous balloon mitral valvuloplasty',
#   'Percutaneous coronary intervention',
#   'Percutaneous valvuloplasty',
#   'Pericardiotomy',
#   'Pharmacological Treatment',
#   'Pharmacotherapy',
#   'Phenprocoumon',
#   'Photochemotherapy',
#   'Phototherapy',
#   'Physical Examination',
#   'PHYSICAL PERFORMANCE',
#   'pilsicainide',
#   'Pindolol',
#   'pioglitazone',
#   'Pirenzepine',
#   'pirfenidone',
#   'Placebos',
#   'Plastic operation on muscle',
#   'Play',
#   'Pleurectomy',
#   'Plug',
#   'Position change',
#   'Positive pressure therapy',
#   'Potassium Channel Blockers',
#   'Pravastatin',
#   'Prenatal Testing',
#   'Prescription of prophylactic anticoagulant',
#   'prescription procedure',
#   'Prescriptions, Drug',
#   'prevention evaluation',
#   'prevention of disorder',
#   'Primary Health Care',
#   'Primary Prevention',
#   'proadrenomedullin',
#   'Probes',
#   'Probucol',
#   'Procainamide',
#   'Procedure on heart',
#   'Procedures',
#   'Procedures on veins',
#   'Propafenone',
#   'Propafenone Hydrochloride',
#   'Prophylactic treatment',
#   'Propofol',
#   'Propranolol',
#   'Prostaglandins',
#   'Prosthesis',
#   'Prosthetic replacement',
#   'Prosthetic valve',
#   'Protamines',
#   'Psychotherapy, Multiple',
#   'Puncture procedure',
#   'Quinidine',
#   'Quinidine Sulfate',
#   'Radiofrequency ablation',
#   'Radiofrequency Ablation Systems',
#   'Ramipril',
#   'ranolazine',
#   'ranpirnase',
#   'Reading',
#   'REBREATHING',
#   'Recombinant Monocyte Chemoattractant Protein-1',
#   'Reconstructive Surgical Procedures',
#   'Recorder',
#   'Rehabilitation therapy',
#   'Relaxation',
#   'remifentanil',
#   'Removal of endotracheal tube',
#   'Removes',
#   'Renin-angiotensin-aldosterone System Inhibitors',
#   'Repair of mitral valve',
#   'Repair of tricuspid valve',
#   'Reparative closure',
#   'Repeat Surgery',
#   'Reperfusion Therapy',
#   'Replacement of mitral valve with tissue graft',
#   'Reporting',
#   'Rest',
#   'resveratrol',
#   'Revascularization - action',
#   'rilmakalim',
#   'Risk Assessment',
#   'Risk Management',
#   'Risk Reduction',
#   'RMS',
#   'Robotic Systems',
#   'rosuvastatin',
#   'Rotundium',
#   'Routine procedure',
#   'Scanning Systems',
#   'Screening procedure',
#   'Screening Tests',
#   'Secondary prevention',
#   'Secondary procedure',
#   'Self-Management',
#   'Semiconductor laser device',
#   'Sensors',
#   'Sleeves',
#   'Sodium Channel Blockers',
#   'Sodium Chloride',
#   'Sotalol',
#   'Sphygmomanometers',
#   'Spironolactone',
#   'split brain',
#   'Sports',
#   'Stabilization',
#   'Stents, Vascular, Coronary',
#   'Steroid therapy',
#   'Stimulation procedure',
#   'Streptokinase',
#   'Stroke prevention',
#   'stroke therapy',
#   'Superoxide Dismutase',
#   'Support, device',
#   'Surgical incisions',
#   'Surgical Management',
#   'Surgical Procedures, Elective',
#   'Surgical Procedures, Endoscopic',
#   'Surgical Procedures, Minimally Invasive',
#   'Surgical Procedures, Thoracoscopic',
#   'Surgical repair',
#   'Surgical Replantation',
#   'Suture ligation',
#   'Sympathectomy',
#   'Symptom control',
#   'Taking medication',
#   'tedisamil',
#   'Telemedicine',
#   'telmisartan',
#   'Termination of pregnancy',
#   'Testosterone',
#   'Theophylline',
#   'Therapeutic agent',
#   'Therapeutic device, NOS',
#   'Therapeutic Effect',
#   'Therapeutic Intervention',
#   'Therapy, Computer-Assisted',
#   'Thiazolidinediones',
#   'Thoracic Surgical Procedures',
#   'Thrombin',
#   'Thrombin Inhibitors',
#   'Thromboembolectomy',
#   'Thrombolytic Therapy',
#   'Ticlopidine',
#   'Total pharyngolaryngectomy',
#   'Transcutaneous Electric Nerve Stimulation',
#   'Transducers',
#   'Transjugular intrahepatic portosystemic shunt procedure',
#   'Transplantation',
#   'Transplantation, Autologous',
#   'Treatment Guidelines',
#   'treatment method',
#   'Treatment Protocols',
#   'triflusal',
#   'Ultrasonic Therapy',
#   'Ultrasound Ablation Catheters',
#   'Univer',
#   'valsartan',
#   'Verapamil',
#   'VERAPAMIL TREATMENT',
#   'Video-Assisted Surgery',
#   'Visit, outpatient',
#   'Vitamin E',
#   'Vitamin K',
#   'Vitamin K antagonist',
#   'Vitamin prophylaxis',
#   'Vitamin supplementation',
#   'von Willebrand Factor',
#   'Warfarin',
#   'Warfarin Sodium',
#   'WARFARIN TREATMENT',
#   'Wavefront analysis',
#   'Xamoterol',
#   'ximelagatran',
#   'zoledronic acid',
#   'Zonal',
#   '{PROVIDER}'
# ]

require 'net/http'
require 'rexml/rexml'
require 'rexml/document'

def get_count(url)
  uri = URI(url)
  s = Net::HTTP.get(uri)


  doc = REXML::Document.new(s)
  count = doc.elements['eSearchResult\Count'].first.text
end



CONGEST_HEART_FAILURE_TREATMENTS.each do |t|
  t = t.gsub(' ', '+')
  first = get_count("http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22#{t}%22")
  second = get_count("http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%22atrial+fibrillation%22+%22#{t}%22")

  puts "#{second.to_f / first.to_f}"
end